# Generated by Django 3.0.7 on 2021-03-14 07:03

import breeding.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('last_cleaned', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Birth_cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=16)),
                ('issued_date', models.DateField()),
                ('cert_file', models.FileField(blank=True, null=True, upload_to='falcon_docs/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Falcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('ring', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('birth_date', models.DateField()),
                ('CITES_num', models.CharField(blank=True, max_length=30, null=True)),
                ('CITES_img', models.FileField(blank=True, null=True, upload_to='falcon_docs/')),
                ('registration_img', models.FileField(blank=True, null=True, upload_to='falcon_docs/')),
                ('RDOS_permission_img', models.FileField(blank=True, null=True, upload_to='falcon_docs/')),
                ('width_young', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_young', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_young', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('width_old', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_old', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_old', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.Birth_cert')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_father', to='breeding.Falcon')),
                ('in_aviary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breeding.Aviary')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_mother', to='breeding.Falcon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('latin', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='falcon_imgs/')),
                ('falcon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.Falcon')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='female_pair', to='breeding.Falcon', validators=[breeding.models.validate_female])),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='male_pair', to='breeding.Falcon', validators=[breeding.models.validate_male])),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=32)),
                ('office_type', models.CharField(choices=[('PIW', 'Powiatowy Inspektorat Weterynarii'), ('RDOS', 'Regionalna Dyrekcja Ochrony Środowiska'), ('MIN', 'Ministerstwo Środowiska'), ('POW', 'Starostwo Powiatowe')], max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='falcon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='breeding.Species'),
        ),
        migrations.AddField(
            model_name='birth_cert',
            name='vet_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='breeding.Office'),
        ),
    ]
