# Generated by Django 3.0.6 on 2020-05-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Falcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('ring', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('species_latin', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('CITES_num', models.CharField(max_length=30)),
                ('CITES_img', models.ImageField(upload_to='')),
                ('registration_img', models.ImageField(upload_to='')),
                ('RDOS_permission_img', models.ImageField(upload_to='')),
                ('width_young', models.PositiveSmallIntegerField()),
                ('length_young', models.PositiveSmallIntegerField()),
                ('weight_young', models.PositiveSmallIntegerField()),
                ('photos_young', models.ImageField(upload_to='')),
                ('width_old', models.PositiveSmallIntegerField()),
                ('length_old', models.PositiveSmallIntegerField()),
                ('weight_old', models.PositiveSmallIntegerField()),
                ('photos_old', models.ImageField(upload_to='')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_father', to='breeding.Falcon')),
                ('in_aviary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeding.Aviary')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_female', to='breeding.Falcon')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_male', to='breeding.Falcon')),
                ('offspring', models.ManyToManyField(to='breeding.Falcon')),
            ],
        ),
        migrations.AddField(
            model_name='falcon',
            name='in_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeding.Pair'),
        ),
        migrations.AddField(
            model_name='falcon',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_mother', to='breeding.Falcon'),
        ),
        migrations.AddField(
            model_name='falcon',
            name='siblings',
            field=models.ManyToManyField(related_name='_falcon_siblings_+', to='breeding.Falcon'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='falcons',
            field=models.ManyToManyField(to='breeding.Falcon'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeding.Pair'),
        ),
    ]
