# Generated by Django 3.0.7 on 2021-04-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='falcon',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'samiec'), ('F', 'samica')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='breeding.Species'),
        ),
    ]
