# Generated by Django 3.0.6 on 2020-05-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='breeding.Falcon'),
        ),
    ]
