# Generated by Django 3.0.6 on 2020-05-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0002_auto_20200512_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='CITES_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='CITES_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='RDOS_permission_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_father', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='in_aviary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breeding.Aviary'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='in_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breeding.Pair'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='length_old',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='length_young',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_mother', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='photos_old',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='photos_young',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='registration_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='ring',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='siblings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_falcon_siblings_+', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='species',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='species_latin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='weight_old',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='weight_young',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='width_old',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='width_young',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
