# Generated by Django 3.0.7 on 2021-05-02 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breeding', '0002_auto_20210418_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falcon',
            name='CITES_img',
        ),
        migrations.RemoveField(
            model_name='falcon',
            name='CITES_num',
        ),
        migrations.AddField(
            model_name='falcon',
            name='CITES_nr',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='CITES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=16)),
                ('issued_date', models.DateField()),
                ('cites_file', models.FileField(blank=True, null=True, upload_to='falcon_docs/')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='breeding.Office')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='falcon',
            name='CITES',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.CITES'),
        ),
    ]
