# Generated by Django 3.0.6 on 2020-05-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0004_auto_20200518_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviary',
            name='last_cleaned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
