# Generated by Django 3.0.7 on 2021-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0004_remove_falcon_cites_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cites',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
