# Generated by Django 3.0.7 on 2021-05-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0005_auto_20210503_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='CITES',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.CITES'),
        ),
    ]
