# Generated by Django 3.0.7 on 2021-05-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0006_auto_20210503_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='CITES',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.CITES', unique=True),
        ),
    ]
