# Generated by Django 3.0.6 on 2020-05-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0008_auto_20200518_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='falcon_imgs/')),
            ],
        ),
        migrations.AlterField(
            model_name='falcon',
            name='photos_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_photos_old', to='breeding.Photo'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='photos_young',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_photos_young', to='breeding.Photo'),
        ),
    ]
