# Generated by Django 3.0.7 on 2022-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0009_auto_20210503_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'samiec'), ('F', 'samica'), ('U', 'nieznana')], max_length=1, null=True),
        ),
    ]
