# Generated by Django 3.0.6 on 2020-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0009_auto_20200518_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falcon',
            name='species_latin',
        ),
        migrations.AlterField(
            model_name='falcon',
            name='species',
            field=models.CharField(blank=True, choices=[('F.p.', 'Falco peregrinus'), ('F.ch.', 'Falco cherrug'), ('F.r.', 'Falco rusticolus')], max_length=5, null=True),
        ),
    ]
