# Generated by Django 3.0.6 on 2020-05-24 17:28

import breeding.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0011_auto_20200519_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='breeding.Falcon', validators=[breeding.models.validate_female]),
        ),
        migrations.AlterField(
            model_name='pair',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='breeding.Falcon', validators=[breeding.models.validate_male]),
        ),
    ]
