# Generated by Django 3.0.6 on 2020-06-05 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breeding', '0012_auto_20200524_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='falcon',
            name='owner',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
