# Generated by Django 3.0.7 on 2020-09-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0014_falcon_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=32)),
                ('office_type', models.CharField(choices=[('PIW', 'Powiatowy Inspektorat Weterynarii'), ('RDOS', 'Regionalna Dyrekcja Ochrony Środowiska'), ('MIN', 'Ministerstwo Środowiska'), ('POW', 'Starostwo Powiatowe')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='aviary',
            name='occupied',
        ),
        migrations.AddField(
            model_name='aviary',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aviary',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.Pair'),
        ),
    ]
