# Generated by Django 3.0.7 on 2020-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0016_auto_20200928_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_falcon_siblings_+', to='breeding.Falcon'),
        ),
    ]
