# Generated by Django 3.0.7 on 2020-09-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0017_auto_20200928_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falcon',
            name='siblings',
        ),
        migrations.AddField(
            model_name='falcon',
            name='youngsters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_youngsters', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_father', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_mother', to='breeding.Falcon'),
        ),
    ]
