# Generated by Django 3.0.7 on 2020-09-30 08:05

import breeding.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0018_auto_20200928_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='breeding.Falcon', validators=[breeding.models.validate_female]),
        ),
        migrations.AlterField(
            model_name='pair',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='breeding.Falcon', validators=[breeding.models.validate_male]),
        ),
        migrations.RemoveField(
            model_name='pair',
            name='offspring',
        ),
        migrations.AddField(
            model_name='pair',
            name='offspring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.Falcon'),
        ),
    ]
