# Generated by Django 3.0.7 on 2020-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0019_auto_20200930_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
