# Generated by Django 3.0.7 on 2020-10-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0021_auto_20201002_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falcon',
            name='in_pair',
        ),
    ]
