# Generated by Django 3.0.7 on 2020-10-09 12:01

import breeding.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0022_remove_falcon_in_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='female', to='breeding.Falcon', validators=[breeding.models.validate_female]),
        ),
        migrations.AlterField(
            model_name='pair',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='male', to='breeding.Falcon', validators=[breeding.models.validate_male]),
        ),
    ]
