# Generated by Django 3.0.7 on 2020-10-09 12:11

import breeding.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0023_auto_20201009_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_father', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_mother', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='photos_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='falcon_photos_old', to='breeding.Photo'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='photos_young',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='falcon_photos_young', to='breeding.Photo'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='breeding.Species'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='youngsters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_youngsters', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='female_pair', to='breeding.Falcon', validators=[breeding.models.validate_female]),
        ),
        migrations.AlterField(
            model_name='pair',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='male_pair', to='breeding.Falcon', validators=[breeding.models.validate_male]),
        ),
    ]
