# Generated by Django 3.0.7 on 2020-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0025_auto_20201009_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='youngsters',
            field=models.ManyToManyField(related_name='_falcon_youngsters_+', to='breeding.Falcon'),
        ),
    ]
