# Generated by Django 3.0.7 on 2020-10-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0026_auto_20201009_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falcon',
            name='youngsters',
        ),
        migrations.AlterField(
            model_name='falcon',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_father', to='breeding.Falcon'),
        ),
        migrations.AlterField(
            model_name='falcon',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falcon_mother', to='breeding.Falcon'),
        ),
    ]
