# Generated by Django 3.0.7 on 2020-11-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0030_birth_cert_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcon',
            name='birth_cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='breeding.Birth_cert'),
        ),
    ]
